name: CI Pipeline

on: 
  push:
     branches: [ main ]

jobs:
   build: 
     runs-on: ubuntu-latest
     steps: 
     - name: Checkoout code
       uses: actions/checkout@v5

     - name: Set up Node.js
       uses: actions/setup-node@v3
       with: 
           node-version: 16
      
     - name: Install dependencies 
       run: npm install

   tests:
      runs-on: ubuntu-latest
      needs: build
      steps:
        - name: Runs test
          uses: npm test