name: CI Pipeline

on: 
  push:
     branches: [ main ]

  pull_request:
     branches: [ main ]
  
  workflow_dispatch:
  
  schedule: 
    - cron: "0 2 * * *" # minutes hours month days week

jobs:
   build: 
     runs-on: ubuntu-latest
     steps: 
     - name: Checkoout code
       uses: actions/checkout@v5

     - name: Set up Node.js
       uses: actions/setup-node@v3
       with: 
           node-version: 16
      
     - name: Install dependencies 
       run: npm install

     - name: Upload build artifact
       uses: actions/upload-artifact@v4
       with:
         name: build-files
         path: dist/

     - name: Notify whenever the build fails
       if: failure()
       run: echo "Build failed!!"

   tests:
      runs-on: ubuntu-latest
      needs: build
      steps:
        - name: Checkoout code
          uses: actions/checkout@v5

        - name: Runs test
          run: npm test

   security_scan: 
      runs-on: ubuntu-latest
      needs: tests
      steps:
        - name: Checkoout code
          uses: actions/checkout@v5
        
        - name: Run filesystem security_scan
          uses: aquasecurity/trivy-action@7b7aa264d83dc58691451798b4d117d53d21edfe
          with: 
            scan-type: fs
            scan-ref: .
            vuln-type: os, library
            output: 'trivy-results.json'
            format: json
            exit-code: 0

        - name: Upload scan results as an artifact
          uses: actions/upload-artifact@v4
          with: 
             name: trivy-results
             path: trivy-results.json

